### ISSUE TITLE
"Show a replay" button doesn't work with the new format (base65536)

### ISSUE THREAD

**Issue by flarn2006** [ferno/hatetris#1]
I tried to watch the world record replay as listed in the base65536 repository, but it wouldn't work. When I tried the hex version, it did. Since it doesn't even output the hex format anymore, this is obviously a problem, as the replays it gives you don't work at all. I think it should accept (and output, why not) both formats.

**Comment by ferno** [comment]
Ah, the code here on GitHub has diverged slightly from the live code on qntm.org. Sorry about that. I have fixed this with [this commit](https://github.com/ferno/hatetris/commit/e9c61c9c31b912d086dfb8229aa5b9c2a401cae3), along with a fairly huge refactor to bring this codebase out of 2010, and [redeployed the new distribution](https://qntm.org/files/hatetris/hatetris.html).

Cheers
